// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20230417002807_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "T-Shirt",
                            Description = "Camiseta geek",
                            ImageURL = "https://static3.tcdn.com.br/img/img_prod/460977/camiseta_masculina_unissex_jogos_classicos_nintendo_video_game_arcade_donkey_kong_sonic_preta_ev_98685_1_ec026f63f3151195828a42c0f48b2e45.jpg",
                            Name = "Camiseta geek jogos",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Bone",
                            Description = "Bone geek",
                            ImageURL = "https://static3.tcdn.com.br/img/img_prod/460977/camiseta_masculina_unissex_jogos_classicos_nintendo_video_game_arcade_donkey_kong_sonic_preta_ev_98685_1_ec026f63f3151195828a42c0f48b2e45.jpg",
                            Name = "Bone Super Mario",
                            Price = 49.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Book",
                            Description = "Livro geek",
                            ImageURL = "https://static3.tcdn.com.br/img/img_prod/460977/camiseta_masculina_unissex_jogos_classicos_nintendo_video_game_arcade_donkey_kong_sonic_preta_ev_98685_1_ec026f63f3151195828a42c0f48b2e45.jpg",
                            Name = "Livro Sonic",
                            Price = 59.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Action Figure",
                            Description = "Boneco geek",
                            ImageURL = "https://static3.tcdn.com.br/img/img_prod/460977/camiseta_masculina_unissex_jogos_classicos_nintendo_video_game_arcade_donkey_kong_sonic_preta_ev_98685_1_ec026f63f3151195828a42c0f48b2e45.jpg",
                            Name = "Logo Nintendo",
                            Price = 69.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
